ignore-generated-header = true
severity = "warning"
confidence = 0.8

[rule.package-comments]
[rule.else]
[rule.names]
  severity = "error"
[rule.var-declaration]
[rule.unexported-return]
[rule.time-names]
[rule.receiver-names]
[rule.range]
[rule.increment-decrement]
[rule.if-return]
[rule.exported]
[rule.errors]
[rule.errorf]
[rule.error-strings]
[rule.error-return]
[rule.dot-imports]
[rule.context-key-types]
[rule.context-arguments]
[rule.blank-imports]