ignore-generated-header = true
severity = "warning"
confidence = 0.8

[rule.package-comments]
[rule.else]
[rule.names]
[rule.argument-limit]
  arguments = [2]
[rule.cyclomatic]
  severity = "error"
  arguments = [3]